src/blueprints/main/models.py
import traceback
from distutils.util import strtobool
from flask import current_app
from ... import db


class Setting(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    value = db.Column(db.Text())

    defaults = {"maintenance": False, "explore_db": False}

    def __init__(self, name=None, value=None):
        self.id = None
        self.name = name
        self.value = value

    def set_maintenance(self, mode):
        maintenance = Setting.query.filter(Setting.name == "maintenance").first()

        if maintenance is None:
            value = self.defaults["maintenance"]
            maintenance = Setting(name="maintenance", value=str(value))
            db.session.add(maintenance)

        mode = str(mode)

        try:
            if maintenance.value != mode:
                maintenance.value = mode
                db.session.commit()
            return True
        except Exception as e:
            current_app.logger.error(
                "Cannot set maintenance to {0}. DETAIL: {1}".format(mode, e)
            )
            current_app.logger.debug(traceback.format_exec())
            db.session.rollback()
            return False

    def toggle(self, setting):
        current_setting = Setting.query.filter(Setting.name == setting).first()

        if current_setting is None:
            value = self.defaults[setting]
            current_setting = Setting(name=setting, value=str(value))
            db.session.add(current_setting)

        try:
            if current_setting.value == "True":
                current_setting.value = "False"
            else:
                current_setting.value = "True"
            db.session.commit()
            return True
        except Exception as e:
            current_app.logger.error(
                "Cannot toggle setting {0}. DETAIL: {1}".format(setting, e)
            )
            current_app.logger.debug(traceback.format_exec())
            db.session.rollback()
            return False

    def set(self, setting, value):
        current_setting = Setting.query.filter(Setting.name == setting).first()

        if current_setting is None:
            current_setting = Setting(name=setting, value=None)
            db.session.add(current_setting)

        value = str(value)

        try:
            current_setting.value = value
            db.session.commit()
            return True
        except Exception as e:
            current_app.logger.error(
                "Cannot edit setting {0}. DETAIL: {1}".format(setting, e)
            )
            current_app.logger.debug(traceback.format_exec())
            db.session.rollback()
            return False

    def get(self, setting):
        if setting in self.defaults:
            result = self.query.filter(Setting.name == setting).first()
            if result is not None:
                return (
                    strtobool(result.value)
                    if result.value in ["True", "False"]
                    else result.value
                )
            else:
                return self.defaults[setting]
        else:
            current_app.logger.error("Unknown setting queried: {0}".format(setting))

    def init_db(self):
        for k, v in self.defaults.items():
            self.set(k, v)

src/blueprints/main/forms.py
from flask_babel import gettext as _
from wtforms import HiddenField, SelectField, StringField, SubmitField
from wtforms.validators import Optional, DataRequired

from ..firewall.consts import LOG_LEVELS
from ...forms.frm import frm
from ..firewall.structure import permanent


class frm_change_zone(frm):
    ZONES = [(zones, zones) for zones in permanent.getZoneNames()]
    new_zone = SelectField(label=_("New zone"), choices=ZONES)
    source = HiddenField(label=_("Source"))
    type = HiddenField(label=_("Type"))
    submit = SubmitField(label=_("Save"))


class frm_logs(frm):
    search = StringField(
        label=_("Search"),
        validators=[Optional()],
    )

    LOG_LEVELS.append(("", "---"))
    level = SelectField(
        label=_("Level"),
        default="",
        validators=[Optional()],
        choices=LOG_LEVELS,
    )

    type = SelectField(
        label=_("Type"),
        default="firewall",
        validators=[DataRequired()],
        choices=[("system", "System Log"), ("firewall", "Denied Log")],
    )

    date_start = HiddenField()
    date_end = HiddenField()
    submit = SubmitField(label=_("OK"))

src/blueprints/main/routes.py
import datetime
from flask import (
    Blueprint,
    current_app,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    escape,
)
from flask.helpers import url_for
from flask_security import auth_required, current_user, permissions_required

from .forms import frm_change_zone, frm_logs
from .models import Setting
from ..firewall.structure import STRUCTURE
from ..firewall.helpers import context, getLog

main_bp = Blueprint("main", __name__)


@main_bp.before_app_request
def before_app_request():

    g.collapsed = request.cookies.get("sidebar-collapsed", False) == "true"

    # Check site is in maintenance mode
    maintenance = Setting().get("maintenance")
    if (
        maintenance
        and current_user.is_authenticated  # noqa: W503
        and not current_user.has_role("admin")  # noqa: W503
    ):
        return render_template("maintenance.html")

    context()


@main_bp.route("/", methods=["GET"])
@auth_required()
def index():
    structure = STRUCTURE["zones"]
    config_mode = session.get("config_mode", "runtime")
    zones = structure[config_mode]["get_all"]()
    obj = structure[config_mode]["get_item"]
    connections = [
        {zone: interfaces}
        for zone in zones
        if len(interfaces := obj(zone).getInterfaces()) > 0
    ]

    sources = [
        {zone: sources} for zone in zones if len(sources := obj(zone).getSources()) > 0
    ]

    actives_zones = current_app.runtime_config.getActiveZones()
    # logs = LogsView()
    # logs.get(request, args, kwargs)
    return render_template(
        "main.html",
        sources=sources,
        actives_zones=actives_zones,
        connections=connections,
        zones=zones,
        frm_change_zone=frm_change_zone(),
    )


@main_bp.route("/logs", methods=["GET", "POST"])
@auth_required()
@permissions_required("logs-read")
def logs():
    journal = {}
    if request.method == "GET":
        journal = getLog("firewall")

    if request.method == "POST":
        query = request.form.get("search")
        level = request.form.get("level")
        log = request.form.get("type", "denied")
        if start := request.form.get("date_start"):
            start = datetime.datetime.strptime(start, "%Y-%m-%dT%H:%M")
        if end := request.form.get("date_end"):
            end = datetime.datetime.strptime(end, "%Y-%m-%dT%H:%M")
        journal = getLog(log, query, start, end, level)

    return render_template("logs.html", journal=journal, form=frm_logs())


@main_bp.route("/actions", methods=["GET"])
@auth_required()
def actions():
    try:
        if (default_zone := request.args.get("default_zone")) and current_user.has_permission("changezone"):
            current_app.runtime_config.setDefaultZone(zone=default_zone)

        if config_mode := request.args.get("config_mode"):
            session["config_mode"] = config_mode

        if (denied_log := request.args.get("denied_log")) and current_user.has_permission("logs-write"):
            current_app.runtime_config.setLogDenied(denied_log)

        if (panic_mode := request.args.get("panic_mode")) and current_user.has_permission("panicmode"):
            if panic_mode == "False":
                current_app.runtime_config.enablePanicMode()
            else:
                current_app.runtime_config.disablePanicMode()

        if (automatic_helpers := request.args.get("automatic_helpers")) and current_user.has_permission("automatichelper"):
            current_app.runtime_config.setAutomaticHelpers(automatic_helpers)

        if (lockdown_mode := request.args.get("lockdown_mode")) and current_user.has_permission("lockdown"):
            if lockdown_mode == "False":
                current_app.runtime_config.enableLockdown()
            else:
                current_app.runtime_config.disableLockdown()

        if request.args.get("reload"):
            current_app.runtime_config.reload()

        if request.args.get("runtimetopermanent") and current_user.has_permission("permanent"):
            current_app.runtime_config.runtimeToPermanent()

    except Exception as error:
        flash(error)

    return redirect(escape(request.referrer))


@main_bp.route("/changezone", methods=["POST"])
@auth_required()
@permissions_required("changezone-write")
def changezone(changezone=None):
    structure = STRUCTURE["zones"]
    config_mode = "permanent"
    obj = STRUCTURE["zones"][config_mode]["get_item"]
    s_del = STRUCTURE["zones"]["sources"]["del"]
    s_add = STRUCTURE["zones"]["sources"]["add"]
    i_del = STRUCTURE["zones"]["interfaces"]["del"]
    i_add = STRUCTURE["zones"]["interfaces"]["add"]
    form = frm_change_zone()
    if form.validate_on_submit():
        source = form.cleaned_data["source"]
        new_zone = form.cleaned_data["new_zone"]
        try:
            if form.cleaned_data.get("type") == "interface":
                old_zone = STRUCTURE["zones"][config_mode]["get_zoi"](source)
                old_obj = obj(old_zone)
                new_obj = obj(new_zone)
                getattr(old_obj, i_del)(source)
                getattr(new_obj, i_add)(source)
            if form.cleaned_data.get("type") == "source":
                old_zone = STRUCTURE["zones"][config_mode]["get_zos"](source)
                old_obj = obj(old_zone)
                new_obj = obj(new_zone)
                getattr(old_obj, s_del)(source)
                getattr(new_obj, s_add)(source)

            if config_mode == "runtime" and (
                set_item := structure.get(config_mode, {}).get("set_item")
            ):
                set_item(old_zone, old_obj)
                set_item(new_zone, new_obj)

        except Exception as error:
            flash(error, "error")

    return redirect(url_for("main.index"))

src/blueprints/user/routes.py
from flask import Blueprint, current_app, render_template, request
from flask_security import auth_required, current_user, permissions_required

from ... import db
from ..main.models import Setting
from .forms import frm_user_profile
from .models import Role, User

user_bp = Blueprint(
    "accounts", __name__, template_folder="templates", url_prefix="/accounts"
)


@user_bp.route("/profile", methods=["GET", "POST"])
@auth_required()
def profile():
    form = frm_user_profile()
    if request.method == "GET":
        profile = User.query.filter_by(username=current_user.username).first()
        form = frm_user_profile(obj=profile)

    if form.validate_on_submit():
        user = User.query.filter_by(username=current_user.username).first()
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()

    return render_template("profile_user.html", form=form)


@user_bp.route("/advanced", methods=["GET", "POST"])
@auth_required()
@permissions_required("admin-write", "admin-read")
def advanced():

    role = Role.query.filter_by(name="dba").first()
    if request.method == "POST":
        Setting().set_maintenance(request.form.get("maintenance") == "on")
        if request.form.get("explore_db") == "on":
            current_app.user_datastore.add_role_to_user(current_user, role)
            db.session.commit()
        else:
            current_app.user_datastore.remove_role_from_user(current_user, role)
            db.session.commit()

    dict = {
        "maintenance": bool(Setting().get("maintenance")),
        "explore_db": current_user.has_role("dba"),
    }
    return render_template("profile_adv.html", **dict)

src/templates/admin.html
{% import 'admin/layout.html' as layout with context -%}
{% import 'admin/static.html' as admin_static with context %}
{% import 'admin/actions.html' as actionslib with context %}
{% extends "base.html" %}
{% set section="admin" %}
{% block title%}
{% if admin_view.category %}{{ admin_view.category }} - {% endif %}{{ admin_view.name }} - {{ admin_view.admin.name }}
{% endblock%}
{% block extracss %}
    {% if admin_view.extra_css %}
        {% for css_url in admin_view.extra_css %}
        <link href="{{ css_url }}" rel="stylesheet">
        {% endfor %}
    {% endif %}
    <style>
        .hide {
            display: none;
        }
    </style>
    {# {% block head %} {% endblock %} #}
    {% block head_tail %} {% endblock %}
{% endblock %}

{% block content %}
<div id="adminviewer" class="overflow-auto">
  {% block messages %}{{ layout.messages() }}{% endblock %}
  {% set render_ctx = h.resolve_ctx() %}
  {% block fa_body %}{% endblock %}
</div>
{% endblock %}

{% block extrascripts%}
{% if admin_view.extra_js %}
    {% for js_url in admin_view.extra_js %}
        <script src="{{ js_url }}" type="text/javascript"></script>
    {% endfor %}
{% endif %}
{% block tail %}{% endblock %}    
{% endblock%}

src/templates/footer.html
 <nav class="navbar navbar-expand-lg navbar-light bg-light px-2 py-0">
    <ul class="navbar-nav">
        <span><strong><a href="https://github.com/cyr-ius/firewall-ui">{{ SITE_NAME }}</a> <small>v{{VERSION}}</small></strong><small> Copyright &copy; 2021 - All rights reserved.</small></span>
    </ul>
    <ul class="navbar-nav ms-md-auto">
        <span class="navbar-text">Automatic Helpers:</span>
        <li class="nav-link dropup">
                <a class="text-reset text-decoration-none dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ g.automatic_helpers }}
                </a>
                <ul class="dropdown-menu" style="">
                    <li><a class="dropdown-item" href="{{ url_for('main.actions', automatic_helpers='yes') }}">yes</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('main.actions', automatic_helpers='no') }}">no</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('main.actions', automatic_helpers='system') }}">system</a></li>
                </ul>
        </li>
        <span class="navbar-text px-1">Denied log:</span>
        <li class="nav-link dropup">
                <a class="text-reset text-decoration-none dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ g.denied_log }}
                </a>
                <ul class="dropdown-menu" style="">
                    <li><a class="dropdown-item" href="{{ url_for('main.actions', denied_log='all') }}">all</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('main.actions', denied_log='unicast') }}">unicast</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('main.actions', denied_log='broadcast') }}">broadcast</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('main.actions', denied_log='multicast') }}">multicast</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('main.actions', denied_log='off') }}">off</a></li>
                </ul>
        </li>
        <span class="navbar-text px-1">Panic mode</span>
        <li class="nav-link px-2">
            <div class="form-check form-switch">
                <input class="form-check-input header-checkbox" type="checkbox" {% if panic_mode %}checked{% endif %} onclick="location.href='{{ url_for('main.actions', panic_mode=g.panic_mode) }}';">
            </div>
        </li>
        <span class="navbar-text px-1">Lockdown</span>
        <li class="nav-link px-2">
            <div class="form-check form-switch">
                <input class="form-check-input header-checkbox" type="checkbox" {% if g.lockdown_mode %}checked{% endif %} onclick="location.href='{{ url_for('main.actions', lockdown_mode=g.lockdown_mode) }}';">
            </div>
        </li>        
    </ul>
</nav>

src/templates/navbar.html
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light pb-1 pt-0 pe-1">
        <ul class="navbar-nav">
            <li class="nav-item mt-2 ms-3">
                <a role="button" type="button"id="sidebarCollapse"><i class="bi bi-justify"></i></a>
            </li>
            <span class="navbar-text ms-3">Mode:</span>
            <li class="nav-item">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <span class="text-danger">{{ session.config_mode }}</span>
                    </a>
                    <ul class="dropdown-menu" style="">
                        <li><a class="dropdown-item" href="{{ url_for('main.actions', config_mode='runtime') }}">Runtime</a></li>
                        {% if current_user.has_permission("permanent") %}
                        <li><a class="dropdown-item" href="{{ url_for('main.actions', config_mode='permanent') }}">Permanent</a></li>
                        {% endif %}
                    </ul>
            </li>   
            <span class="navbar-text ms-3">Default Zone: </span>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="defaultZoneDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ g.default_zone }}
                </a>
                <div class="dropdown-menu" aria-labelledby="defaultZoneDropdown" style="z-index:1030">
                    {% for zone in g.zones%}
                    <a class="dropdown-item" href="{{ url_for('main.actions', default_zone=zone) }}">{{zone}}</a>
                    {% endfor %}
                </div>
            </li>                                
        </ul> 
        <ul class="navbar-nav ms-md-auto">
                {% if session.config_mode == 'permanent' and current_user.has_permission("section-write") %}
                <div class="btn-group">
                {% if section and item %}
                    <button id="section_delete" class="btn btn-danger btn-sm" data-message="Are you sur to delete {{item}} ?" data-uri="{{url_for('api.section.item', section=section, item=item)}}">
                        <span>{{ _("Delete") }}</span>
                    </button>
                    <button id="section_reset" class="btn btn-warning btn-sm" data-message="Are you sur to reset {{item}} ?" data-uri="{{url_for('api.section.reset', section=section, item=item)}}">
                        <span>{{ _("Reset") }}</span>
                    </button>
                    <button class="btn btn-secondary btn-sm" type="button" data-bs-toggle="modal" data-bs-target="#modal_edit_section">
                        <span>{{ _("Edit")}}</span>
                    </button>
                {% endif %}
                    <button class="btn btn-success btn-sm dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="{{ 'visually-hidden' if section and item }}">{{ _("New") }}</span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="sectionDropdownMenu" style="z-index:1030;">
                        {% for label in g.modal_sections.keys() %}
                        <li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#modal_new_{{label}}" data-uri="{{ url_for('api.section.section', section=label) }}">{{ _(label.capitalize()) }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}        
            <li class="nav-item"><a class="btn btn-secondary btn-sm ms-2" href="{{ url_for('main.actions', reload=true) }}"><i class="bi-load"></i>Reload</a></li>
            <li class="nav-item"><a class="btn btn-secondary btn-sm ms-2" href="{{ url_for('main.actions', completreload=true) }}">Full Reload</a></li>
            {% if current_user.has_permission("permanent") %}
            <li class="nav-item"><a class="btn btn-secondary btn-sm ms-2" href="{{ url_for('main.actions', runtimetopermanent=true) }}">To Permanent</a></li>
            {% endif %}
        </ul>   
</nav>
{% endblock %}

src/templates/sidebar.html
{% block sidebar %}
<nav class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
    <a id="brand" href="/" class="d-flex align-items-center py-1  mb-md-0 me-md-auto text-white text-decoration-none">
        <img id="logo" class="d-inline-block me-3" src="{{ url_for('static', filename='img/firewall-applet.png') }}" width="28">
        <span class="fs-6 d-sm-inline">{{ SITE_NAME }}</span>
    </a>
    <hr class="my-0" style="width:100%;" />
    <ul class="navbar-nav flex-column mb-auto align-items-center align-items-sm-start" id="menu">
        {% if current_user.has_permission("zones-read") %}
        <li class="nav-item">
            <a class="nav-link px-0 align-middle text-white {% if section == 'zones' %}active{% endif %}" data-bs-toggle="collapse" data-bs-target="#zones-collapse" aria-expanded="{{ 'true' if section == 'zones'  else 'false' }}" href="#">
                <i class="bi bi-layers-half"></i><span class="ms-1 d-sm-inline">Zones</span>
            </a>
            <div id="zones-collapse" class="collapse nav flex-column ms-1 {% if section == 'zones' and g.collapsed==false %}show{% endif %}" data-bs-parent="#sidebar" >
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small navbar-nav-scroll" style="--bs-scroll-height: 400px;">
                    {% for zone in g.zones %}
                    <li>
                        <a class="{{ active(request.path, '/'+ zone +'/') }}" href="{{ url_for('firewall.generic_tab', section='zones', item=zone, tabname='services') }}">{{zone}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </li>    
        {% endif %}
        {% if current_user.has_permission("services-read") %}
        <li class="nav-item">
            <a class="nav-link px-0 align-middle text-white {% if section == 'services' %}active{% endif %}" data-bs-toggle="collapse" data-bs-target="#services-collapse" aria-expanded="{{ 'true' if section == 'services'  else 'false' }}" href="#">
                <i class="bi bi-box-seam"></i><span class="ms-1 d-sm-inline">Services</span>
            </a>
            <div id="services-collapse" class="collapse nav flex-column ms-1 {% if section == 'services' and g.collapsed==false %}show{% endif %}" data-bs-parent="#sidebar">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small navbar-nav-scroll"  style="--bs-scroll-height: 400px;">
                    {% for service in g.services %}
                    <li>
                        <a class="link-dark {{ active(request.path,'/'+ service +'/') }}" href="{{ url_for('firewall.generic_tab', section='services', item=service, tabname='ports') }}">{{service}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </li>
        {% endif %}
        {% if current_user.has_permission("ipsets-read") %}
        <li class="nav-item">
            <a class="nav-link px-0 align-middle text-white {% if section == 'ipsets' %}active{% endif %}" data-bs-toggle="collapse" data-bs-target="#ipsets-collapse" aria-expanded="{{ 'true' if section == 'ipsets'  else 'false' }}" href="#">
                <i class="bi bi-bricks"></i><span class="ms-1 d-sm-inline">IPsets</span> 
            </a>
            <div id="ipsets-collapse" class="collapse  nav flex-column ms-1 {% if section == 'ipsets' and g.collapsed==false  %}show{% endif %}" data-bs-parent="#sidebar">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small navbar-nav-scroll"  style="--bs-scroll-height: 400px;">
                    {% for ipset in g.ipsets %}
                    <li>
                        <a class="link-dark {{ active(request.path,'/'+ ipset +'/') }}" href="{{ url_for('firewall.generic_tab', section='ipsets', item=ipset, tabname='inputs') }}">{{ipset}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </li>
        {% endif %}
        {% if current_user.has_permission("icmptypes-read") %}
        <li class="nav-item">
            <a class="nav-link px-0 align-middle text-white {% if section == 'icmptypes' %}active{% endif %}" data-bs-toggle="collapse" data-bs-target="#icmptypes-collapse" aria-expanded="{{ 'true' if section == 'icmptypes'  else 'false' }}" href="#">
                <i class="bi bi-code-square" aria-hidden="true"></i><span class="ms-1 d-sm-inline">ICMP Types</span>
            </a>
            <div id="icmptypes-collapse" class="collapse nav flex-column ms-1 {% if section == 'icmptypes' and g.collapsed==false  %}show{% endif %}" data-bs-parent="#sidebar">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small navbar-nav-scroll"  style="--bs-scroll-height: 400px;">
                    {% for icmptype in g.icmptypes %}
                    <li>
                        <a class="link-dark {{ active(request.path,'/'+ icmptype +'/') }}" href="{{ url_for('firewall.generic_tab', section='icmptypes', item=icmptype, tabname='destination') }}">{{icmptype}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </li>
        {% endif %}
        {% if current_user.has_permission("helpers-read") %}
        <li class="nav-item">
            <a class="nav-link align-middle px-0 text-white {% if section == 'helpers' %}active{% endif %}" data-bs-toggle="collapse" data-bs-target="#assistants-collapse" aria-expanded="{{ 'true' if section == 'helpers'  else 'false' }}" href="#">
                <i class="bi bi-life-preserver" aria-hidden="true"></i><span class="ms-1 d-sm-inline">Helpers</span>
            </a>
            <div id="assistants-collapse" class="collapse nav flex-column ms-1 {% if section == 'helpers' and g.collapsed==false  %}show{% endif %}" data-bs-parent="#sidebar">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small navbar-nav-scroll"  style="--bs-scroll-height: 400px;">
                    {% for helper in g.helpers %}
                    <li>
                        <a class="link-dark {{ active(request.path,'/'+ helper+'/') }}" href="{{ url_for('firewall.generic_tab', section='helpers', item=helper, tabname='ports') }}">{{helper}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </li>
        {% endif %}
        {% if current_user.has_permission("directconfigs-read") %}
        <li class="nav-item">
            <a class="nav-link align-middle px-0 text-white {% if section == 'directconfigs' %}active{% endif %}"  href="{{ url_for('firewall.specific_tab', section='directconfigs', tabname='chains')}}">
                <i class="bi bi-bullseye" aria-hidden="true"></i><span class="ms-1 d-sm-inline">Direct config</span>
            </a>
        </li>
        {% endif %}
        {% if current_user.has_permission("whitelists-read") %}
        <li class="nav-item">
            <a class="nav-link align-middle px-0 text-white {% if section == 'whitelists' %}active{% endif %}" href="{{ url_for('firewall.specific_tab', section='whitelists', tabname='contexts') }}">
                <i class="bi bi-lock" aria-hidden="true"></i><span class="ms-1 d-sm-inline">White list</span>
            </a>
        </li>
        {% endif %}
        {% if current_user.has_permission("logs-read") %}
        <li class="nav-item">
            <a class="nav-link align-middle px-0 text-white {% if section == 'logs' %}active{% endif %}" href="{{ url_for('main.logs')}}">
                <i class="bi bi-newspaper"></i><span class="ms-1 d-sm-inline">Logs</span>
            </a>
        </li>
        {% endif %}
        {% if current_user.has_role("admin") or current_user.has_role("dba") %}
        <li class="nav-item">
            <a class="nav-link align-middle px-0  text-white text-decoration-none {% if section == 'admin' %}active{% endif %}" data-bs-toggle="collapse" href="#admin_menu">
                <i class="bi bi-speedometer2"></i><span class="ms-3 d-sm-inline">Administration</span>
            </a>
            <ul class="collapse nav flex-column ms-1 {% if section == 'admin' %}show{% endif %}" id="admin_menu" data-bs-parent="#menu">
                {% import 'admin/layout.html' as layout with context -%}
                {{ layout.menu() }}
            </ul>
        </li>   
        {% endif %}           
    </ul>
     <hr>
    <div class="dropdown dropup pb-1">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            {%if current_user.gravatar_url %}
            <img src="{{current_user.gravatar_url}}" alt="hugenerd" width="30" height="30" class="rounded-circle">
            {% else %}
            <i class="bi-person" style="font-size:30px"></i>
            {% endif %}
            <span class="d-none d-sm-inline mx-1">{{ current_user.username}}</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="{{ url_for('accounts.profile')}}">Profile</a></li>
            <li><a class="dropdown-item" href="{{ url_for_security('change_password')}}">Change Password</a></li>
            <li><a class="dropdown-item" href="{{ url_for_security('two_factor_setup')}}">TOTP</a></li>
            {% if current_user.has_role('admin')%}
            <li><a class="dropdown-item" href="{{ url_for('accounts.advanced')}}">Advanced settings</a></li>
            {% endif %}
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" onclick="location.href='{{ url_for_security('logout') }}';">Sign out</a></li>
        </ul>
    </div>     
</nav>
{% endblock %}